operatorNamespace: rook-ceph

cephClusterSpec:
  cephVersion:
    image: nexus.local:8122/ceph/ceph:v19.2.0
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  network:
    provider: host
  crashCollector:
    disable: false
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "worker1"
      devices:
      - name: "/dev/sdb"
      config:
        storeType: bluestore
        crushRoot: "worker1"
    - name: "worker2"
      devices:
      - name: "/dev/sdb"
      config:
        storeType: bluestore
        crushRoot: "worker2"
    - name: "worker3"
      devices:
      - name: "/dev/sdb"
      config:
        storeType: bluestore
        crushRoot: "worker3"

# Storage class definitions
cephBlockPools:
- name: hdd-pool
  spec:
    failureDomain: host
    crushRoot: "worker1"
    replicated:
      size: 1  # Local storage
  storageClass:
    enabled: true
    name: rook-ceph-hdd
    isDefault: false
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    parameters:
      pool: rook-ceph-hdd
      imageFormat: "2"
      imageFeatures: layering

- name: nvme-pool-worker2
  spec:
    failureDomain: host
    crushRoot: "worker2"
    replicated:
      size: 1
  storageClass:
    enabled: true
    name: rook-ceph-nvme2
    isDefault: false
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    parameters:
      pool: nvme-pool-worker2
      crushRoot: "worker2"
      imageFormat: "2"
      imageFeatures: layering

- name: nvme-pool-worker3
  spec:
    failureDomain: host
    crushRoot: "worker3"
    replicated:
      size: 1
  storageClass:
    enabled: true
    name: rook-ceph-nvme3
    isDefault: false
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    parameters:
      pool: nvme-pool-worker3
      crushRoot: "worker3"
      imageFormat: "2"
      imageFeatures: layering

# Enable monitoring
monitoring:
  enabled: false

# Dashboard configuration with SSL
dashboard:
  enabled: true
  ssl: true
  ingress:
    enabled: true
    ingressClassName: nginx
    host:
      name: ceph.k8s.local
      path: /
    tls:
    - hosts:
        - ceph.k8s.local
      secretName: ceph-dashboard-cert
    annotations:
      cert-manager.io/cluster-issuer: "default-issuer"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"

# Enable the Ceph toolbox for debugging
toolbox:
  enabled: true
  resources:
    limits:
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

# Additional settings
allowMultipleFilesystems: true
