apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://nexus.local/repository/nginx-ingress-helm-proxy/
      targetRevision: 4.12.0
      chart: ingress-nginx
      helm:
        valueFiles:
          - values.yaml
    - repoURL: https://github.com/BenRachmiel/k8s.local
      targetRevision: HEAD
      path: ./
      ref: values
      directory:
        include: "ingress-cert.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
