apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-default-cert
  namespace: default
spec:
  secretName: ingress-default-cert
  issuerRef:
    name: default-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.k8s.local"
