controller:
  image:
    registry: nexus.local:8122
    image: ingress-nginx/controller
    tag: "v1.12.0"
    digest: ""
  
  admissionWebhooks:
    patch:
      image:
        registry: nexus.local:8122
        image: ingress-nginx/kube-webhook-certgen
        tag: "v1.5.0"
        digest: ""

  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.3.75"
    externalTrafficPolicy: Local

  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"

  ingressClassResource:  # Changed from ingressClass to ingressClassResource
    name: nginx
    create: true
    default: true       # Changed from setAsDefaultIngress to default

  extraArgs:
    default-ssl-certificate: "default/ingress-default-cert"

defaultBackend:
  enabled: true
  image:
    registry: nexus.local:8122
    image: defaultbackend-amd64
    tag: "1.5"
    digest: ""

rbac:
  create: true
