apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: default-issuer
    kind: ClusterIssuer
  dnsNames:
    - argocd.k8s.local
    - argocd-server
    - argocd-server.argocd
    - argocd-server.argocd.svc
    - argocd-server.argocd.svc.cluster.local
