apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://nexus.local/repository/prometheus-helm-proxy/
      chart: kube-prometheus-stack
      targetRevision: 68.1.0
      helm:
        valueFiles:
          - $values/argocd/applications/monitoring/monitoring-stack-values.yaml
    - repoURL: https://github.com/BenRachmiel/k8s.local
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://nexus.local/repository/grafana-helm-proxy/
      chart: loki
      targetRevision: 6.24.0
      helm:
        valueFiles:
          - $values/argocd/applications/monitoring/loki-values.yaml
    - repoURL: https://github.com/BenRachmiel/k8s.local
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://nexus.local/repository/grafana-helm-proxy/
      chart: promtail
      targetRevision: 6.16.6
      helm:
        valueFiles:
          - $values/argocd/applications/monitoring/promtail-values.yaml
    - repoURL: https://github.com/BenRachmiel/k8s.local
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
