apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://nexus.local/repository/portainer-helm-proxy/
      chart: portainer
      targetRevision: 1.0.59
      helm:
        valueFiles:
          - $values/argocd/applications/portainer/values.yaml
    - repoURL: https://github.com/BenRachmiel/k8s.local
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
