image:
  repository: nexus.local:8122/portainer/portainer-ce

service:
  type: ClusterIP

tls:
  force: true

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "default-issuer"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: portainer.k8s.local
      paths:
        - path: /
  tls:
    - secretName: portainer-tls
      hosts:
        - portainer.k8s.local

persistence:
  storageClass: rook-ceph-hdd
