apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://nexus.local/repository/nvidia-helm-proxy/
      targetRevision: v24.9.1
      chart: gpu-operator
      helm:
        valueFiles:
          - nvidia-operator-values.yaml
    - repoURL: https://github.com/BenRachmiel/k8s.local
      targetRevision: HEAD
      path: ./
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
