apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
