# argocd/applications/metallb.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BenRachmiel/k8s.local.git
    targetRevision: HEAD
    path: infrastructure/networking/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    # For all resources
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/resourceVersion
        - /metadata/uid
        - /metadata/generation
        - /metadata/annotations/kubectl.kubernetes.io/last-applied-configuration
        - /status
    # Deployment specific
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/deployment.kubernetes.io/revision
        - /metadata/labels/app.kubernetes.io/instance
    # DaemonSet specific
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /metadata/annotations/deprecated.daemonset.template.generation
        - /metadata/labels/app.kubernetes.io/instance
    # Service specific
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /metadata/labels/app.kubernetes.io/instance
